name: private_fin_data_platform
version: 1.0.0
config-version: 2

profile: private_fin_data_platform

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: target
clean-targets:
  - target
  - dbt_packages

vars:
  enable_paypay_home_loan_schedule: false

seeds:
  private_fin_data_platform:
    reference:
      +database: DATAWAREHOUSE_DB
      +schema: REFERENCE
      +quote_columns: false

models:
  private_fin_data_platform:
    staging:
      +database: DATAWAREHOUSE_DB
      +schema: STAGING
      +materialized: table
