name: Terraform Deployment (AWS Dev)

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [ main ]
    paths:
      - 'terraform/aws/platform/dev/**'
      - '.github/workflows/terraform-aws-dev.yml'
  workflow_dispatch:

env:
  TARGET_ENV: "dev"

permissions:
  id-token: write
  contents: read

jobs:
  terraform_aws_dev:
    name: Terraform AWS Dev Apply
    runs-on: ubuntu-latest
    environment: dev-infra
    defaults:
      run:
        working-directory: ./terraform/aws/platform/${{ env.TARGET_ENV }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v7

      - name: Configure AWS Credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/github-actions-tfstate-access-role
          aws-region: ap-northeast-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: 1.15.9

      - name: Terraform Init
        run: |
          terraform init \
            -backend-config="bucket=arn:aws:s3:ap-northeast-1:${{ vars.AWS_ACCOUNT_ID }}:accesspoint/${{ vars.PROJECT_PREFIX }}-${{ env.TARGET_ENV }}-tfstate-ap" \
            -backend-config="use_lockfile=true" \
            -backend-config="encrypt=true"

      - name: Terraform Plan to AWS Dev
        run: terraform plan -no-color -out=tfplan
        env:
          TF_VAR_env:                  ${{ env.TARGET_ENV }}
          TF_VAR_project_prefix:       ${{ vars.PROJECT_PREFIX }}
          TF_VAR_sf_user_arn:          ${{ vars.SF_USER_ARN }}
          TF_VAR_sf_external_id:       ${{ vars.SF_EXTERNAL_ID }}
          TF_VAR_snowpipe_queue_arn:   ${{ vars.AWS_S3_SNOWPIPE_QUEUE_ARN }}

      - name: Terraform Apply to AWS Dev
        run: terraform apply -no-color tfplan
        env:
          TF_VAR_env:                  ${{ env.TARGET_ENV }}
          TF_VAR_project_prefix:       ${{ vars.PROJECT_PREFIX }}
          TF_VAR_sf_user_arn:          ${{ vars.SF_USER_ARN }}
          TF_VAR_sf_external_id:       ${{ vars.SF_EXTERNAL_ID }}
          TF_VAR_snowpipe_queue_arn:   ${{ vars.AWS_S3_SNOWPIPE_QUEUE_ARN }}
